"""
Wiki Engine — HayekSwarm knowledge base with Obsidian vault support.

Provides the API layer for the LLM Wiki skill, including:
- Obsidian vault configuration
- Wiki CRUD operations (ingest, query, lint, search, export)
- Cross-referencing and consistency maintenance
- Integration with the marketplace (agents bid on wiki tasks)
"""

from __future__ import annotations

import os
import re
import json
import shutil
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

WIKI_PATH = Path(os.environ.get("WIKI_PATH", Path.home() / "wiki"))

SCHEMA_STRUCTURE: dict[str, str] = {
    "raw/articles": "Immutable web articles, clippings",
    "raw/papers": "PDFs, arxiv papers, research documents",
    "raw/transcripts": "Meeting notes, interviews, transcripts",
    "raw/assets": "Images, diagrams referenced by sources",
    "entities": "Entity pages (people, orgs, products, models, papers)",
    "concepts": "Concept/topic pages — definitions, explanations",
    "comparisons": "Side-by-side analyses of two or more things",
    "queries": "Filed query results worth keeping",
}

OBSIDIAN_VAULT = WIKI_PATH / ".obsidian"
OBSIDIAN_TEMPLATES = OBSIDIAN_VAULT / "templates"


# ── Wiki Initialization ──────────────────────────────────────────────────────


def init_wiki(path: Optional[Path] = None) -> dict[str, Any]:
    """Initialize the wiki directory structure if it doesn't exist.

    Creates the three-layer architecture + Obsidian vault config.

    Returns:
        Dict with status, path, and stats.
    """
    wiki_path = Path(path) if path else WIKI_PATH
    wiki_path = wiki_path.expanduser().resolve()

    # Create directory structure
    created = []
    for subdir, _desc in SCHEMA_STRUCTURE.items():
        d = wiki_path / subdir
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            created.append(str(d.relative_to(wiki_path)))

    # Create core files if they don't exist
    core_files = {
        wiki_path / "SCHEMA.md": _generate_schema(wiki_path),
        wiki_path / "index.md": "# HayekSwarm Wiki\n\n## Index\n\n<!-- Auto-generated by agents. One-line summaries per page. -->\n",
        wiki_path / "log.md": f"# Wiki Log\n\nStarted: {datetime.now().isoformat()}\n\n| Date | Action | Agent | Details |\n|------|--------|-------|--------|\n",
    }
    for fpath, content in core_files.items():
        if not fpath.exists():
            fpath.write_text(content)
            created.append(str(fpath.relative_to(wiki_path)))

    # Copy Obsidian vault config from skill directory
    _install_obsidian_vault(wiki_path)

    return {
        "status": "initialized" if created else "already_exists",
        "path": str(wiki_path),
        "created": created,
        "total_dirs": len(SCHEMA_STRUCTURE),
        "total_files": sum(1 for _ in wiki_path.rglob("*.md") if ".obsidian" not in str(_)),
    }


def _install_obsidian_vault(wiki_path: Path) -> None:
    """Install .obsidian vault config from the skill's bundled config."""
    # Find the bundled .obsidian directory
    skill_dir = Path(__file__).parent.parent / "skills" / "wiki" / ".obsidian"
    if not skill_dir.exists():
        logger.warning("Bundled .obsidian config not found at %s", skill_dir)
        return

    vault_dir = wiki_path / ".obsidian"
    if vault_dir.exists():
        return  # Don't overwrite existing vault config

    # Copy vault config
    shutil.copytree(skill_dir, vault_dir, dirs_exist_ok=True)
    logger.info("Installed Obsidian vault config at %s", vault_dir)


def _generate_schema(wiki_path: Path) -> str:
    """Generate the SCHEMA.md file."""
    lines = [
        "# HayekSwarm Wiki — Schema",
        "",
        "## Structure",
        "",
        "```",
    ]
    for subdir, desc in SCHEMA_STRUCTURE.items():
        lines.append(f"{subdir}/  # {desc}")
    lines.extend([
        "```",
        "",
        "## Conventions",
        "",
        "- **Naming**: lowercase-with-hyphens.md",
        "- **Frontmatter**: Always include type, tags, created, status",
        "- **Statuses**: seedling → growing → evergreen",
        "- **Tags**: Use `entity`, `concept`, `comparison`, `query`",
        "- **Cross-references**: Use [[wikilinks]] — the agent maintains these",
        "- **Log**: Append to log.md for every action taken",
        "",
        "## Domain Config",
        "",
        "Set WIKI_PATH env var to change wiki location. Default: ~/wiki",
    ])
    return "\n".join(lines)


# ── Wiki Operations ──────────────────────────────────────────────────────────


def get_wiki_stats(path: Optional[Path] = None) -> dict[str, Any]:
    """Get statistics about the wiki."""
    wiki_path = Path(path) if path else WIKI_PATH
    wiki_path = wiki_path.expanduser().resolve()

    if not wiki_path.exists():
        return {"error": "Wiki not initialized", "path": str(wiki_path)}

    md_files = list(wiki_path.rglob("*.md"))
    vault_files = [f for f in md_files if ".obsidian" not in str(f)]

    # Count by layer
    layers = {"raw": 0, "entities": 0, "concepts": 0, "comparisons": 0, "queries": 0, "other": 0}
    for f in vault_files:
        rel = f.relative_to(wiki_path)
        for layer in layers:
            if str(rel).startswith(layer):
                layers[layer] += 1
                break
        else:
            layers["other"] += 1

    # Count cross-references ([[wikilinks]])
    cross_refs = 0
    for f in vault_files:
        content = f.read_text(encoding="utf-8", errors="ignore")
        cross_refs += len(re.findall(r"\[\[([^\]]+)\]\]", content))

    return {
        "path": str(wiki_path),
        "total_pages": len(vault_files),
        "layers": layers,
        "cross_references": cross_refs,
        "has_obsidian_vault": (wiki_path / ".obsidian").exists(),
        "has_schema": (wiki_path / "SCHEMA.md").exists(),
        "has_index": (wiki_path / "index.md").exists(),
        "recent_log_entries": _get_recent_log(wiki_path, 5),
    }


def _get_recent_log(wiki_path: Path, n: int = 5) -> list[str]:
    """Get the last n entries from the wiki log."""
    log_path = wiki_path / "log.md"
    if not log_path.exists():
        return []
    lines = log_path.read_text(encoding="utf-8", errors="ignore").splitlines()
    # Find log entries (lines starting with |)
    entries = [l for l in lines if l.startswith("|")]
    return entries[-n:]


def search_wiki(
    query: str,
    path: Optional[Path] = None,
    max_results: int = 10,
) -> list[dict[str, Any]]:
    """Search wiki pages by keyword."""
    wiki_path = Path(path) if path else WIKI_PATH
    wiki_path = wiki_path.expanduser().resolve()

    if not wiki_path.exists():
        return []

    results = []
    query_lower = query.lower()
    for f in wiki_path.rglob("*.md"):
        if ".obsidian" in str(f):
            continue
        content = f.read_text(encoding="utf-8", errors="ignore")
        if query_lower in content.lower():
            # Find the match context
            lines = content.splitlines()
            match_lines = [
                i for i, l in enumerate(lines) if query_lower in l.lower()
            ]
            results.append({
                "path": str(f.relative_to(wiki_path)),
                "title": f.stem,
                "matches": len(match_lines),
                "snippet": lines[min(match_lines[0], len(lines) - 1)].strip()[:200] if match_lines else "",
            })
            if len(results) >= max_results:
                break

    return results


def query_wiki(
    question: str,
    path: Optional[Path] = None,
) -> dict[str, Any]:
    """Query the wiki for relevant context.

    Searches all pages for relevant content and returns context
    that can be used to answer the question. The actual answering
    is done by the council agent that wins the auction.
    """
    wiki_path = Path(path) if path else WIKI_PATH
    wiki_path = wiki_path.expanduser().resolve()

    # Search for relevant pages
    results = search_wiki(question, wiki_path, max_results=5)

    # Read orientation files
    schema = ""
    index = ""
    if (wiki_path / "SCHEMA.md").exists():
        schema = (wiki_path / "SCHEMA.md").read_text(encoding="utf-8", errors="ignore")[:2000]
    if (wiki_path / "index.md").exists():
        index = (wiki_path / "index.md").read_text(encoding="utf-8", errors="ignore")[:2000]

    return {
        "question": question,
        "relevant_pages": results,
        "schema_preview": schema[:500],
        "index_preview": index[:500],
    }


def get_wiki_export(path: Optional[Path] = None) -> dict[str, Any]:
    """Get wiki contents for Obsidian vault export."""
    wiki_path = Path(path) if path else WIKI_PATH
    wiki_path = wiki_path.expanduser().resolve()

    if not wiki_path.exists():
        return {"error": "Wiki not initialized"}

    pages = []
    for f in sorted(wiki_path.rglob("*.md")):
        if ".obsidian" in str(f):
            continue
        pages.append({
            "path": str(f.relative_to(wiki_path)),
            "size": f.stat().st_size,
            "modified": datetime.fromtimestamp(f.stat().st_mtime).isoformat(),
        })

    return {
        "path": str(wiki_path),
        "total_pages": len(pages),
        "pages": pages,
        "vault_config": {
            "has_obsidian": (wiki_path / ".obsidian").exists(),
            "templates": list((OBSIDIAN_TEMPLATES).rglob("*.md")) if OBSIDIAN_TEMPLATES.exists() else [],
        },
    }